[package]
name = "ton-tlb-serialize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tlb_macro = {path = "tlb_macro"}
